# Database credentials for the dev environment. Spec: 005-platform-delivery FR-013.
# Encrypted with SOPS: the keys stay readable so a change can be reviewed, the values do not.
apiVersion: v1
kind: Secret
metadata:
    name: flagpole-postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:0/xOciViVYU=,iv:yjb2sGCaOOS0J47lYsROdZ2AwLOd5ImmSIHkKJ5Z9uI=,tag:4Poggry82gNHjA4e7j8JoA==,type:str]
    password: ENC[AES256_GCM,data:1EzSwKuJAsx84Ko58lmC7xvlbdjlfHbZSCnreKaYE3aUq1PvGMb2E2oX8rh97Br7,iv:HU8V5RMT0tdfZn+EpBQ1rXQGM3R3UIOjcyw0KQ7k3cQ=,tag:4I3NwJBdeYKlpWGnkkAgzQ==,type:str]
    database-url: ENC[AES256_GCM,data:RgBd77C7MKgDZAAQF7b5eDgzM69qYcg/bEMsgerbi7xv3uGNMYwdTtUBS0xPbG7XmhKc1e0QQs6ePY30/PY/caLxyeyyEL5X+Gl9nc2KMy+SZtiTnBRtTZpUzktPa3H7h0j0rWaoofVJgtI0X5ipZicaPOgkj/0VEBSKeNideusw20MW,iv:CbzOSlumTJ/PM8+YlMuAuTYBiORXbjj3kbutyPK6R5w=,tag:dA+YN1n2URcXR7z/kzrGqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWlcydnBwazI5dUVFU1d6
            UGdPbFlKUlBDTUVmOHRheGNiVC9oYVQ4eVg4CnFSYkI3elArUjJzeUlQVXcxMGtr
            cHd3R0huOVljOWhrZElPODJoUGNwRGMKLS0tIHBwaU5pajBBc1hPYUMrTHVpQzB3
            ajUxMzhzVFBXMnN2MFd2MmhVSmJyamcKbimJVkQmhE2J9n3D5bS2LglSmsGsYiZZ
            0OqPv1ftx/cIPF9LQXAiKkkRqTswCZ+obkdfAC1kIYGkovrK5aG1TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agu0nx8jekfrhpc8ez88az3spg884a5mtq97c3c57vqn8rmvv5tq5myvhn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T21:30:31Z"
    mac: ENC[AES256_GCM,data:Q582qaOH9bfihT1jC+QZKMZR+Kc3lrNdM4CdjMRaI2REk1nQAt69q/JCoO6MYWaF6hPupBCtx3UWoaHqyapfbbOp1feP6PHB1KDkfC/ZgD2eSaW68k8MPP0Un/tiF34Jmu95QbAQop4CDpJ9K2CoOK+cUIiJ9kIgo68oSz6w1iQ=,iv:+r0IuOCQiJwQSdHgjrETsdc2jlPhIYFsxqSk9lLooJM=,tag:3TEt9y+mESmtKzZlR7XFig==,type:str]
    version: 3.13.3
