/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List flags with both environments' state (FR-006) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ordered by key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Flag"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a flag; both envs disabled at 0 (FR-003) — operator */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FlagCreate"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Flag"];
                    };
                };
                400: components["responses"]["Invalid"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description flag already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flags/{key}/env/{env}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set enabled + rollout for one environment; writes an audit entry (FR-004, FR-005) — operator */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                    env: components["schemas"]["Env"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EnvState"];
                };
            };
            responses: {
                /** @description updated flag */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Flag"];
                    };
                };
                400: components["responses"]["Invalid"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description unknown flag */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate a flag for a user in an environment (FR-008..010) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EvaluateRequest"];
                };
            };
            responses: {
                /** @description decision (never 404) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvaluateResponse"];
                    };
                };
                400: components["responses"]["Invalid"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log newest first, cursor-paged, optional flag filter (FR-007) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description return entries with id < before */
                    before?: number;
                    flag_key?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditPage"];
                    };
                };
                400: components["responses"]["Invalid"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** liveness (FR-013) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Status"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** readiness = data store reachable (FR-013) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus text format (FR-013) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Env: "dev" | "prod";
        /** @enum {string} */
        Reason: "env_disabled" | "rollout_hit" | "rollout_miss" | "unknown_flag";
        Error: {
            detail: string;
        };
        Status: {
            /** @enum {string} */
            status?: "ok";
        };
        EnvState: {
            enabled: boolean;
            rollout_percent: number;
        };
        FlagCreate: {
            key: string;
            /** @default  */
            description: string;
        };
        Flag: {
            key: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            environments: {
                dev: components["schemas"]["EnvState"];
                prod: components["schemas"]["EnvState"];
            };
        };
        EvaluateRequest: {
            flag_key: string;
            env: components["schemas"]["Env"];
            user_id: string;
        };
        EvaluateResponse: {
            enabled: boolean;
            reason: components["schemas"]["Reason"];
        };
        AuditEntry: {
            id: number;
            who: string;
            /** Format: date-time */
            at: string;
            flag_key: string;
            env: components["schemas"]["Env"] | null;
            before: components["schemas"]["EnvState"] | null;
            after: Record<string, never>;
        };
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            next_before: number | null;
        };
    };
    responses: {
        /** @description invalid input */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description operator role required */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
