"""initial schema. Spec: 001-flagpole-api FR-016 (data-model.md).

Revision ID: 0001
Revises:
Create Date: 2026-09-02 07:25:47.026346
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flags",
        sa.Column("key", sa.String(length=63), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("who", sa.String(length=320), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("flag_key", sa.String(length=63), nullable=False),
        sa.Column("env", sa.String(length=8), nullable=True),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["flag_key"], ["flags.key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_log_flag_key_id", ["flag_key", "id"], unique=False)

    op.create_table(
        "flag_environments",
        sa.Column("flag_key", sa.String(length=63), nullable=False),
        sa.Column("env", sa.String(length=8), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("rollout_percent", sa.Integer(), nullable=False),
        sa.CheckConstraint("env IN ('dev','prod')", name="ck_flag_environments_env"),
        sa.CheckConstraint(
            "rollout_percent BETWEEN 0 AND 100", name="ck_flag_environments_rollout"
        ),
        sa.ForeignKeyConstraint(["flag_key"], ["flags.key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("flag_key", "env"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flag_environments")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_log_flag_key_id")

    op.drop_table("audit_log")
    op.drop_table("flags")
    # ### end Alembic commands ###
